apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jvm-build-suite-component-vqob
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jvm-build-suite-component-vqob
    app.kubernetes.io/part-of: jvm-build-suite-application-ofsz
  name: jvm-build-suite-component-vqob
  namespace: jvm-build-swvl-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: jvm-build-suite-component-vqob
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: jvm-build-suite-component-vqob
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images@sha256:71eea4213b1593b2c532cf65bb039dfe9afa5768c2363934e5a81963d17889e7
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
